---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/dahston/instavote-deploy

